language: python
sudo: false
matrix:
  include:
  - python: '3.5'
    env: DEPS="numpy scipy nose cython" RUN_EXAMPLES=false
  - python: '3.4'
    env: DEPS="numpy scipy nose cython" RUN_EXAMPLES=false
#  - python: '3.3'
#    env: DEPS="numpy scipy nose cython" RUN_EXAMPLES=false
  - python: '2.7'
    env: DEPS="numpy scipy nose cython" RUN_EXAMPLES=false
  - python: '3.5'
    env: DEPS="numpy scipy nose cython" RUN_EXAMPLES=true

install:
- wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh
  -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda${TRAVIS_PYTHON_VERSION:0:1}/bin:$PATH
- conda update --yes --no-deps conda
- conda config --set always_yes yes --set changeps1 no
- conda update --yes conda
- conda install --yes -c conda conda-env
- conda install --yes $DEPS pip python=${TRAVIS_PYTHON_VERSION}
- pip install coveralls
- python setup.py install
script:
- nosetests -vv --with-coverage --cover-package=abel abel/tests
- | 
    if [ $RUN_EXAMPLES ]; then
        pip install matplotlib==1.5.3
        cd examples/
        set -o pipefail
        for f in ./*example*.py; do
           python $f >> log.txt
        done
    else
        touch log.txt
    fi
    cat log.txt && if grep -q "Traceback (most recent call last):" ~/log.txt; then false; else true; fi

deploy:
  provider: pypi
  user: DanHickstein
  password:
    secure: RlJ41NowzFZ57pzbCQNTnm2OY5tSoCocbassn03GEzWrUqDnVG/jtvqWxf5bKdJ5T1WrFmjeI6/GWGx9Xk5HXAfWQLJjtmtrN/SYerBtdUAEyyV0s//o/Wd2qEB3tj8FCtUAx+mf5Q9ck3mRCFuYqK9rApXXxeUOqCE3R6pnEf/Ubpg7NYqMphziZA65qClqJNl1RFxBRD8mVoik99IrLitka6UnctFMBMWhchuGP80FTG5kyl6sIvVn1cwQISSF3Yr+IVqiKQGL1syRnef4FzOhn5sY4tZwR50cEF1CdAAZQU5GqiFwMKTjmocT/YIMVViJm6/SukJUzPeZNC7YuQBb9ZGroF257PgYyrnGkEK6qs3i3qexRI2c2uLmq19H0FbBtNo1ZHYUF6kzmga+7dW9brzd7zLU2em+nqN7w09JO1Z9gFfHIC5XD276bkwtIK5qT0r7SjNY/HdO/HYaSCLI+FR4R/XpTzC+vWIkhpdv3WZ5IpdIFn9f1SW3Uq4hyro0wlojb26TUyidSIzHDYgPepxLVy5YPuT8Css0kqMh5j9uZeTCqMkyeeSrTBOF64NO6w7RH5cLTYGXMixMNudzHY8yZfH9NaynG+dRwwyy7okFg5D8qKT4zMJfn3yvzg1DAENqz2/cNL38epDEXRruTR99qGnN+xMG2WE/WRs=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: PyAbel/PyAbel
